### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by G-Vishaal** [3fon3fonov/trifon#10]
Hi, i run a windows 10 and tried to run your program with python idle.It's showing me the same error:
Traceback (most recent call last):
  File "F:\Germany intern\trifon-master\gui.py", line 81, in <module>
    fit=rv.signal_fit(name='session')
  File "./lib\RV_mod\__init__.py", line 1505, in __init__
    self.init_transit_params()
  File "./lib\RV_mod\__init__.py", line 1792, in init_transit_params
    self.tr_params = batman.TransitParams()       #object to store transit parameters
AttributeError: module 'batman' has no attribute 'TransitParams'

How do i solve this error?

**Comment by 3fon3fonov** [comment]
You have installed another "batman", most likely via pip.

pip install batman --> wrong 

pip install batman-package --> correct

Remove the old and install the new and the tool will work. I still recommend to use the bash script installers.

**Comment by 3fon3fonov** [comment]
For Windows 10, please read README_for_installation. It is not that trivial but it works 

![ES_Windows_10](https://user-images.githubusercontent.com/44244057/59463868-41c7e980-8e27-11e9-9f8a-95d01cbf3d76.png)

**Comment by G-Vishaal** [comment]
It worked,thank you!
