### ISSUE TITLE
period at top

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#15]
I suggest to put period on top in planet parameter listing, instead of amplitude.
Period is more important. Also the comparison with the periodogram is easier when period is at the top.

**Comment by 3fon3fonov** [comment]
There is a historical reason why the Amplitude is first. Generally, we fit sine-like signals to data. 
Modeling the data with a sine-wave the first parameter usually is the Amplitude, then is the frequency/Period and then the phase. But OK, I can try to put the period on top. The thing is that I have to rearrange the RVmod structure and that takes time. I will keep this in mind and will not close this thread until I made my mind if the period should be on top or not. Thanks for the suggestion.

**Comment by mzechmeister** [comment]
Oh, please try to fix. It is so confusing to check, which period was picked-up .

**Comment by 3fon3fonov** [comment]
Finally done.....
