### ISSUE TITLE
wrong batman package

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#17]
I still I don't have the right batman package. A warning would be good. Change

https://github.com/3fon3fonov/trifon/blob/ecf3a143af07748ad312525c06bd4efee1207614/lib/RV_mod/__init__.py#L1399
to
```python
        try:
           self.init_transit_params()
        except:
            print("You have probably the wrong batman packages.")
```

Then at least it runs (and I don't need to install it).

**Comment by 3fon3fonov** [comment]
See #19

**Comment by 3fon3fonov** [comment]
OK Mathias, 

I just included a similar (but more sophisticated) fix. Now if you don't have batman or you have the wrong one, you should still be able to boot the ES and use the RV part including the mcmc and Nest. Samp, Orbital Evol, etc. Tell me if it works because I dont have the "wrong" batman.

**Comment by mzechmeister** [comment]
https://github.com/3fon3fonov/trifon/blob/5ecd80462bc9bddfac9d9efc408331c83fda0e25/gui.py#L58
does not catch
```
Traceback (most recent call last):
  File "gui.py", line 55, in <module>
    bat_test = batman.TransitParams()
AttributeError: module 'batman' has no attribute 'TransitParams'
```

So change to:
```python
    except (ImportError, KeyError, AttributeError) as e:        
```

**Comment by mzechmeister** [comment]
Ok. Now it is implemented and works.
