### ISSUE TITLE
Label highest periodogram peak

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#18]
It would be good to label the periodogram peak.
I'm too lazy to click and check `print info` content.
It could be none, the highest or more peaks, maybe selectable via a spin button next to cross hair.

**Comment by 3fon3fonov** [comment]
This is done. For more controls on the peak, labels see the new tab Plot opt. --> GLS/TLS.
I would like to receive feedback from you. Tell me if this is what you wanted or not.

More options on the GLS plots will be included and stored in a user config file. But this is now with a lower priority.

**Comment by mzechmeister** [comment]
I like that the periods are still labelled as period in frequency space.
But the labels are misplaced.

**Comment by mzechmeister** [comment]
Here are two screenshots:
![Screenshot_20191009_090203](https://user-images.githubusercontent.com/32583239/66458618-76fde480-ea73-11e9-90b3-54a8551d026d.png)
![Screenshot_20191009_090304](https://user-images.githubusercontent.com/32583239/66458685-a01e7500-ea73-11e9-801a-a2caedee1b75.png)

They are correctly placed in the "RV o-c" tab but not in RVs.

**Comment by mzechmeister** [comment]
And labelling can be also displaced in period
![Screenshot_20191009_090627](https://user-images.githubusercontent.com/32583239/66458872-14591880-ea74-11e9-800d-52700234472a.png)
Likely, the positions are not updated when switching?

**Comment by mzechmeister** [comment]
Also periods close to one day are not marked even if highest. Maybe those periods are less likely,
But it is then unexpected that they are adopted as best period.
![Screenshot_20191009_091553](https://user-images.githubusercontent.com/32583239/66459497-651d4100-ea75-11e9-9586-c9b86198e5f6.png)
