### ISSUE TITLE
command line arguments

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#20]
- [x] `session` `nargs='?'` default:None 
- [ ] `-rvfile` `nargs='+'`

`session` is quite urgent given all the testing, restarting, reloading.

**Comment by 3fon3fonov** [comment]
OK, I will try to include such arguments, although these will be more useful in the script version of RVmod (i.e. these RVmod should in principle work independently without the GUI, see the "examples" directory).

**Comment by 3fon3fonov** [comment]
You can now use 
python gui.py -ses \path_to_session\session.ses # for single session

or 

python gui.py -mses \path_to_session\session.mses # for multi-session


I tested it by loading RV data, fitting, saving ses/mses and then importing. All tests passed. At this point, I cannot guarantee that there will be no problems with this method. Test it and let me know if it works for you.

**Comment by mzechmeister** [comment]
Very useful!

I think, it's worth to include it into as a demo in docs|readme.
