### ISSUE TITLE
TLS broken

### ISSUE THREAD

**Issue by JonasKemmer** [3fon3fonov/trifon#21]
Hey Trifon,
seems like the TLS are broken since you included the markings for the peaks. Can you check that?

Regards,
Jonas

**Comment by 3fon3fonov** [comment]
It works with me:

![TLS_is_working](https://user-images.githubusercontent.com/44244057/61042678-f9bfc680-a3d4-11e9-961b-aa2078eeba6e.jpg)

Copy/Paste the output from Stdout/Stderr to help.

**Comment by JonasKemmer** [comment]
It worked for me with with Commit a0a42af018be2a54c83f0205819e6090537750ac
but now (Commit 4acfa3cebbdb162217f3a3d33e001f8f2ec8aa2c) I get this error:
![Error_message](https://user-images.githubusercontent.com/36412279/61045771-cdf40f00-a3db-11e9-8f0d-4269cd110561.png)
If you want I can send you my datafile in a PM.

**Comment by 3fon3fonov** [comment]
Ah Ok, This is fixable. Send details please.

**Comment by 3fon3fonov** [comment]
Jonas, I think now it should be fixed. Please let me know if you still experience problems.

**Comment by JonasKemmer** [comment]
Perfect, thanks a lot!
