### ISSUE TITLE
error bars color

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#28]
Plot error bars with jitter in gray.
Overplot errors without jitter in corresponding data color.
This is a better visualisation of the jitter.

**Comment by 3fon3fonov** [comment]
In the next release, I will do it, and will report here. I had the same idea in the past. I will definitely try it.

**Comment by 3fon3fonov** [comment]
Mathias hi!, Please git pull the new version and tell me if that's what you wanted. 

Under Plot. opt.-> RV, you will find a checkbox "split jitter". If jitter is added to the plots (i.e. checkbox jitter to plots == True), then the default will be jitter quadratically added to the errorbars with the same color. If split jitter == Ture, then the combined jitter + RV error is plotted with black color, and on top is overplotted the original RV uncertainty.

**Comment by mzechmeister** [comment]
Finally, I found it.
Not intuitive and it does not apply to `RV o-c` and `Extra Plots`
IMO `jitter to plots` and `Split jitter` should be in the same panel.
Also I would replace both by `jitter color` with options `as model` (default), `none`, `as data`, `color`.
If default is  `as model`, then it is clear what is going on.

**Comment by 3fon3fonov** [comment]
> Not intuitive and it does not apply to RV o-c and Extra Plots
Now works for o-c and Extra Plots.

> IMO jitter to plots and Split jitter should be in the same panel.
Done

> Also I would replace both by jitter color with options as model (default), none, as data, color.

I will include more options in the future, including color picker (there, but still inactive)

**Comment by mzechmeister** [comment]
Ok. It works. Still, I would make it `split` default.
