### ISSUE TITLE
unchecking planet does not work

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#30]
![Screenshot_20191009_094404](https://user-images.githubusercontent.com/32583239/66461442-559ff700-ea79-11e9-808b-15cd37fc6a86.png)
The long period (planet 2) was unchecked to fit only planet 1+3. But the program seems to fit planet 1+2.

**Comment by 3fon3fonov** [comment]
Press "init" or type "Enter/Return" to initialize. I can add a signal to that, but it was never needed really. Tell me if that fixed the issue.

**Comment by mzechmeister** [comment]
Ok. So I close this issue.
