### ISSUE TITLE
Adopt best period checks the grey out fields "incl" and "OMEGA" 

### ISSUE THREAD

**Issue by StephanStock** [3fon3fonov/trifon#32]
When you adopt the best period from the residual GLS the exostriker checks the greyed out "incl" and "OMEGA" parameter in case of Kepler fit. If you start an MCMC the MCMC will vary this parameters which is non-sense and takes also away computation time. 

Go around for the moment: switch to dynamical fit and uncheck these parameters then switch back to Kepler fit. Then start MCMC

**Comment by 3fon3fonov** [comment]
Hi Stephan! Thanks for sharing this bug! It should be fixed now, can you "git pull" and try again? Let us know it it works.

**Comment by 3fon3fonov** [comment]
Obviously, this is fixed so I am closing.
