### ISSUE TITLE
1 Wrong data format in line 1 of fortran output, line skipped.

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#34]
```Reading fortran output resulted in 1 warnings:

1 Wrong data format in line 1 of fortran output, line skipped.

===== 2019.10.24 11:10:52 =====
Traceback (most recent call last):
  File "es_gui.py", line 2426, in showDialog_RV_input_file
    self.init_fit()            
  File "es_gui.py", line 2612, in init_fit
    self.update_plots() 
  File "es_gui.py", line 2357, in update_plots
    self.update_RV_plots()
  File "es_gui.py", line 2255, in update_RV_plots
    error_list = self.add_jitter(fit.fit_results.rv_model.rv_err, fit.filelist.idset)
  File "es_gui.py", line 2623, in add_jitter
    errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
  File "es_gui.py", line 2623, in <listcomp>
    errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
IndexError: list index out of range
```
I tried a *rvc.dat and a *.dat

**Comment by 3fon3fonov** [comment]
Hm... the first thing when something like this happens is to recompile the Fortran binaries. I touch the source code a bit last night. it could be that. No problem with me. can you please try to run the bash script? If that's the problem, as a temporary measure I will include an indicator in the GUI if you must recompile after a git pull.

**Comment by mzechmeister** [comment]
Ok, right recompile.
I was too lazy to go through the whole installation procedure. 
Related to #16 and #25, where I suggested a makefile.

**Comment by 3fon3fonov** [comment]
I have an idea of how to make it automatic... let me see if I can succeed

**Comment by 3fon3fonov** [comment]
Auto-compile added! I hope it does the job so the user would never need to deal with recompiling the binaries!
