### ISSUE TITLE
only *.vels files listed

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#6]
When opening RV files via the dialog, only `*.vels` can be selected.
Files with other extensions are not displayed (but at least they can be typed manually and loaded).
I suggest no filter as default and adding more filters (like `*.dat` and `*.txt`).

**Comment by mzechmeister** [comment]
I would also good, if RV filenames could be passed already via the command line, e.g.
```python3 gui.py gj699.harps.dat gj699.keck.dat```

**Comment by 3fon3fonov** [comment]
The .vels filter is there on purpose. This only RV files are loaded. It goes like this:
.vels --> Rvs 
.tran --> Transit light curves
.act --> activity data

if you want to check data, please use the "data inspector".

And since I know you are using .dat files, I will include a custom filter so you can define which data to be filtered/accepted and which not.

**Comment by mzechmeister** [comment]
Thanks.
I never heard about *.tran files.

I appreciate default suffixes. But there should always the possibilty to to see the whole directory content.
So a filter `*` or `*.*` should be added.

**Comment by 3fon3fonov** [comment]
The *.tran suffix is my own idea ;) This tool is evolving, things will definitely change before the first official release. I will make an attempt to make everything as flexible as possible. Thanks for the feedback!

**Comment by 3fon3fonov** [comment]
Ok now I added *.* filter to the "open file" dialog window. It is done to the activity, transit and RV files. First it will show the default .vels, .tran or .act files, but now you will be able to show all files and select whatever you want (e.g. .dat). The files of course should have at least three columns with: time, y, yerr. Bugs are possible, as at the moment I am writing this I had not tested much the file handling. If something is wrong, please let me know.

**Comment by mzechmeister** [comment]
The filter is there, but I can't load any file anymore.

**Comment by 3fon3fonov** [comment]
Strange I dont have this problem. All works fine and I tested it on two different OS systems. do you have an error on the Stdout/stderr tab? post it here so I can help.

**Comment by mzechmeister** [comment]
When loading `datafiles/hip5364.vels`

```
Hi there! Here you can get some more information from the tool's workflow, stdout/strerr, and piped results.

Reading fortran output resulted in 1 warnings:

1 Wrong data format in line 1 of fortran output, line skipped.

===== 2019.06.14 15:06:59 =====
Traceback (most recent call last):
  File "gui.py", line 1663, in showDialog_RV_input_file
    self.init_fit()            
  File "gui.py", line 1835, in init_fit
    self.update_plots() 
  File "gui.py", line 1623, in update_plots
    self.update_RV_plots()
  File "gui.py", line 1532, in update_RV_plots
    error_list = self.add_jitter(fit.fit_results.rv_model.rv_err, fit.filelist.idset)
  File "gui.py", line 1863, in add_jitter
    errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
  File "gui.py", line 1863, in <listcomp>
    errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
IndexError: list index out of range
```

**Comment by 3fon3fonov** [comment]
As I thought. Recompile the fortran routines and all will be fine. Sorry about that but I often work on the fortran routines and each git-push updates the binaries in the repo. Then when you clone you are getting my binaries. just re-run the script every time you clone the newest version.

**Comment by mzechmeister** [comment]
Indeed, it works after recompiling.

Yes, the `*.*` filter helps. I would love if this would be the default or if the last selection is remembered.

The default filter could be a user option in `Settings` in the future...
Drag and drop would be another fancy feature.

**Comment by mzechmeister** [comment]
> Yes, the `*.*` filter helps. I would love if this would be the default or if the last selection is remembered.

I want to give again vote for these feature. (Still annoyed by the vels default. Serval provides *dat).

**Comment by mzechmeister** [comment]
Ok, I reselected the `*.*` filter now more than 100 times.

It is not remembered. Please make it the default.
`vels` is no standard, in particular not for serval.

In long term, the option could be remembered or user customable via `Settings`.

**Comment by 3fon3fonov** [comment]
Done, Now the default is *.* (all files). However, one must be careful and always provide (at least) three columns with BJD [days], RV [m/s], sigmaRV [m/s]. 

In the future, I will make a settings option, so the user will be able to customize the ES as he/she wishes (e.g. default files filters, color schemes, etc.)
