### ISSUE TITLE
jitter is not updated

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#8]
The listed jitter values are always 1.0 m/s.
Are they computed at all?

**Comment by 3fon3fonov** [comment]
Yes, but I guess you are using the LM minimiser. That method as you know cannot fit for jitter, or the chi^2 will get 0 and the jitter infinity. Switch to Simplex and all will be fine.

**Comment by mzechmeister** [comment]
Ok, sure!
I do not noticed it in front of the gui.

**Comment by 3fon3fonov** [comment]
In general, I might remove the LM method. It converges faster than the simplex, but it has it limitations. 
The reason why the LM is still included is that provides instant covariance matrix uncertainties, while I have not yet included uncertainties in the Simplex. The usual scheme is:
1. Run LM to get the best fit without jitter.
2. Using the sollution from 1 Run the Simplex with jitter.
3. Get back to the LM to get errors (but not on the jitters).
4. Or run mcmc to get error for all parameters. 
 
1-3 are super fast. 4 it depends on your mcmc setup, number of parameters, etc.

**Comment by 3fon3fonov** [comment]
Ok the GUI was updated. Now when the "Levenberg-Marquardt" minimization is chosen (by default),
the RV Jitter boxes are de-activated, which should indicate toothe user that these parameters are not fitted. One can still add jitter manually if needed. When the "SImplex" is chosen the boxes are once again active and one can chose to fit, or not to fit the jitter parameters. I hope now is less confusing.

**Comment by mzechmeister** [comment]
Ok, it works.
But for unexperienced user it will be hard to figure this out. Tooltips might help.
